### ISSUE TITLE
Concurrency on the server when accessing db

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#109]
I am running single server instance with multiple workers (up to 10). I have a problem, that sometimes one I post a job to a server multiple client instances start working on it. It causes waste of CPU power but also some inconsistency during cleanup.
I can see that access to database is not atomic - two workers can check that a job is not being worked on, try to start a job a simultaneously write to db that the job is being worked on. 

I might be able to write a patch for that but how should I approach it?

**Comment by inlife** [comment]
how would you approach to solve this problem?

**Comment by franeko** [comment]
Is there an updatedAt value  for each job in db?

Vladyslav Hrytsenko <notifications@github.com> schrieb am Fr. 22. Feb. 2019
um 16:33:

**Comment by inlife** [comment]
yep, every posted job has that field:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-server/src/routes/jobs-create.js

**Comment by franeko** [comment]
We can treat updatedAt as a version of an entry. When a worker sends data
to update it also sends updatedAt value of that entry. We check if the
worker is updating the version currently in the db or if someone updated
that entry in the meantime (that would change the updatedAt value).

Who is setting the new updatedAt value? Server or worker?

Vladyslav Hrytsenko <notifications@github.com> schrieb am Fr. 22. Feb. 2019
um 16:43:

**Comment by inlife** [comment]
>Who is setting the new updatedAt value? Server or worker?

server

Well, I see what you mean, however, shouldn't the same be true for job state?
Since all jobs are queued on the server, as soon as one of the workers picks it up, he sends an update right after changing the job state.

And if I'm not missing anything, and current approach results in misses, using updatedAt would not change that.

Probably the safest way to fix that would be for server to decide which job is taken. A new API method can be introduced, something like `/jobs/pickup`, that will return a job (or empty object/null), and update it's state on the server.

**Comment by adanielyan** [comment]
I had a similar issue with previous version of nexrender. Solved it by assigning a worker ID to every job and making workers query only jobs assigned to them. It guaranteed that only that particular worker will attempt to pickup that job. IDs were assigned to workers on worker start through command line args.
