### ISSUE TITLE
If rendering fails, and the error is in the log file, could that be output to the console?

### ISSUE THREAD

**Issue by misaunde** [inlife/nexrender#111]
I had a render that was failing due to this issue I couldn't figure out: 
https://github.com/inlife/nexrender/issues/110 

but this is how my console output looked:
![image](https://user-images.githubusercontent.com/10051350/53294294-27e39780-37a1-11e9-98f2-a57fc0b28a39.png)

\
Anyways, it took me a while to realize that the job rendering didn't successfully finish, and then, since I'm new, it took a little longer to realize there was another log that contained this information:

![image](https://user-images.githubusercontent.com/10051350/53294274-c4596a00-37a0-11e9-9584-e4dd13587ca8.png)

This might be a dumb question, but is there  any way that that error captured in the log file (which prevented a successful render) could be output directly to the console?

**Comment by inlife** [comment]
actually it's a very good suggestion, i definitely agree that it requires much better error message

**Comment by itsnaresh** [comment]
Because I provided wrong composition name I am getting following error which is wrong[I am running though worker)

Wrong message:
Error:=>Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)
[DglwAofZLyDw5QU_R8vVk] error occurred: Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)

Right Message [Commnad Line Renderer]
ERROR: No comp was found with the given name.

https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/commandLineRenderer.jsx

Question
How can I get these messages in worker so that I can handle them in right way

**Comment by itsnaresh** [comment]
Is there any way that that error captured in the log file (which prevented a successful render) could be output directly to the console?

**Comment by itsnaresh** [comment]
Can I make http REST call from CommnadLineRenderer.jsx file? If yes, can you please let me know how to do that? I want to handle much better error messages
