### ISSUE TITLE
Changing the fill color of a solid 

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#117]
I've got a solid within my presentation and a fill effect applied to it. 

I'd like to edit the color of the fill using nexrender, any idea on how I would go about doing this.

**Comment by inlife** [comment]
For that, could you provide a screenshot of your layer containing the solid in your template project opened after effects interface?

And please make it "unfolded", example:

![](https://user-images.githubusercontent.com/2182108/52443468-7270dd00-2b2e-11e9-8336-255349279c43.png)

**Comment by JamesBotterill** [comment]
![screen shot 2019-02-28 at 12 16 27](https://user-images.githubusercontent.com/9433760/53565921-b5810780-3b52-11e9-9da4-f5423d4f983b.png)


Here's the layer in question

**Comment by inlife** [comment]
Following the example: https://github.com/inlife/nexrender#data-items
Try doing something like this:

```json
{
    "assets": [
        {
            "type": "data",
            "layerName": "scoreboard",
            "property": "Color",
            "value": [1.0, 0.5, 0, 0]
        }
    ]
}
```
(the Color parameter requires a 4 dimensional array [r,g,b,a] of values between 0-1.)
Source: https://www.aenhancers.com/viewtopic.php?t=65

Also, you can set it to change dynamically and use `expression` instead of `value`. Using that approach you will be able to provide an expression that will modify the value of the color on every frame accordingly to your needs.

**Comment by JamesBotterill** [comment]
Sadly I couldn't get this method to work, it still just renders at it's original colour the post refers to expression control > colour control. 

I'll investigate further but I might need to write a expression script to change the colour at the project level

**Comment by inlife** [comment]
If you succeed, please do share it there, I'm very interested in the resolution.

**Comment by JamesBotterill** [comment]
Will do, right now I've created a workaround here I have an image which is being generated from https://dummyimage.com/ and setting the values in the url

**Comment by JamesBotterill** [comment]
do you have a list of supported properties? I've got an expression written that works in the project I just need to find the correct property to apply it to within the json.

**Comment by inlife** [comment]
Unfortunately, I'm not familiar with ExtendScirpting well enough to know how those property lists can be formed. I guess maybe there is some information on the net about that. Or people that actually using scripting a lot might know.

**Comment by JamesBotterill** [comment]
I'm trying to get to grips with the property field within nexrender, how is this mapping to extendscript and how you can define 

For example the color property is a sub property of the colour contol property, which is a sub property of the effect property. 

I'm not sure if this is a feature request to be able to change the values of properties nested in effects.

I'm looking at using a shape instead of a solid but right now, still no joy as again the as the fill color is nested.

**Comment by inlife** [comment]
Well, to see how is it mapped the easiest way is probably to check out the script file that is being generated in the temp work folder for the project. `--skip-cleanup` flag can be added so project won't be cleaned up right away.

basically what you'll see there is something like that:
var property = layer.property(NAME);
property.setValue(VALUE);

In the case of sub-properties, I think it is possible to create a solution to make them work. I didn't actually know there are such things.

**Comment by JamesBotterill** [comment]
I've been looking at this and now have it working in my project but not via nexrender. 

I've got my fill color of the shape being populated from a hex value being entered into a text field, unfortunately I'm trying to update the source text from the json and it's not working. 

I've attached a screen shot for you're thoughts on why the source text might not be updating

<img width="286" alt="screen shot 2019-03-04 at 14 05 03" src="https://user-images.githubusercontent.com/9433760/53739391-8daede00-3e89-11e9-9977-55668c9e0eed.png">

**Comment by inlife** [comment]
well damn, that is quite hacky indeed )
even tho it works very nicely, and props to you for finding that (i don't even imagine how did you discover that)

I think this way might be a bit too complicated for users unfamiliar with AE scripting or js itself.
We should definitely keep this one as a backup option if we fail to find a less verbose solution.

also, funny quote at the end, took me some time to figure out what that meant :D

**Comment by JamesBotterill** [comment]
agreed it's hacky, and it came to me in the shower over the weekend. Then it was just working through the idiosyncrasies of after effects until it works. 

Yes it was a crash course in AE scripting for me too, it's clearly very powerful and equally clunky

**Comment by inlife** [comment]
lets keep this issue open, till we can possibly figure some other way to do that
or as i mentioned before, stick to the way you suggested

**Comment by brassel** [comment]
The problem seems to be that nexrender can not (yet) address subproperties, right?
A good way to add this functionality could be to allow key paths in the `property`  field. For this example it could look like below. Note that this might not be fully correct, since I am not very deep into AE scripting either, but I hope you get the idea. :)

```
{
    "assets": [
        {
            "type": "data",
            "layerName": "scoreboard",
            "property": "Effect.'Color Control'.Color",
            "value": [1.0, 0.5, 0, 0]
        }
    ]
}
```

**Comment by inlife** [comment]
Seems like yes, you are right @brassel.
It is actually a good idea, I guess that would be the best way to solve this.
I think it's better to get rid of `'` in the title, that way would be less confusing for users i think, especially considering the fact that we don't really care if those names have spaces in them, we will do a `split('.')`

```
{
    "assets": [
        {
            "type": "data",
            "layerName": "scoreboard",
            "property": "Effect.Color Control.Color",
            "value": [1.0, 0.5, 0, 0]
        }
    ]
}
```

what do you think @brassel ?

**Comment by brassel** [comment]
Hi Vladyslav,

yes, I think using key paths would greatly increase the things you can do with nexrender!

And also, the `'` will not be strictly necessary here and in most cases.
The decision if you want quoting and backslash escaping is about some assumptions you have to consider:

- are there properties named by the user (you can't keep them from using the dot `.` in their own property names then)
- did AE make the (bad) decision to use properties named "a.b"
- should the approach work in most cases or in all cases

**Comment by JamesBotterill** [comment]
Great to see this being picked up.

For what it's worth I would prefer the property to match the style of extendscript as much as possible.

**Comment by chrisbell08** [comment]
Hey Guys, is this still being worked on?

**Comment by inlife** [comment]
>Hey Guys, is this still being worked on?
Not actively, unfortunately

Actually, @brassel, what if we use `->` as a separator (c++ style), I think its highly unlikely that users might be using that as part of the name.

**Comment by chrisbell08** [comment]
Can I help? I don't mind taking a look if you guys are all busy, would be good if you could just point me in the right direction to save the time digging through all the codebase

**Comment by inlife** [comment]
Sure

So I assume you've read the above comments about how property selection works atm, and how it might be improved.

This is the line of code where it is happening: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/tasks/script.js#L32
(It is being dynamically generated into a script that will be placed into jsx template here: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/nexrender.jsx#L87)

The idea that instead of just doing layer.property("NAME"), we could try doing a sub-property selection via cycle (most likely), unless there is some existing jsx scripting api for that.
So it would result in a sequence of something like
```js
var property = layer
    .property('PART1')
    .property('PART2')
    .property('PART3')
    .property('PART4')
```

Hope that helps more with the direction of what is happening

**Comment by chrisbell08** [comment]
Let me dig into it, will feedback if have any questions :)

**Comment by chrisbell08** [comment]
Ok so taken a different approach here, used expressions and an external js file to control the color. So in the AE template you can add an expression for color, not yet tested for text color but I think the same method will work.

````js
// Model.js
var proposition = {
    color: [0, 0, 0, 1], // [r, g, b, a]
}

// Expression
// Absolute path to our JavaScript model file
var pathToModel = '/path/to/Model.js';
// Evaluate our model
$.evalFile(pathToModel)
// Now the proposition is accessible, return the name property
proposition.color
````

More info on this here: https://www.themarketingtechnologist.co/creating-dynamic-videos-using-javascript-and-after-effects-the-basics/

**Comment by emiliobool** [comment]
First time nexrender user and stumbled into this limitation, I tried a few things before reading the entire thread including the dot syntax and I ended up with just attaching a .jsx script to the main json.

**template.json** (relevant part)
```
{
    "assets": [{
            "src": "file:///.../template.jsx",
            "type": "script"
        }]
}
```

**template.jsx**
```
nexrender.selectLayersByName(null, 'controls', function(layer) {
    layer
        .property('Effects')
        .property('BorderColor')
        .property('Color')
        .setValue([1, 0, 0])
})
```

The issue I have with this approach is I have to overwrite the file every time I want to change the color, I mean it is automated, but it _**feels**_ wrong. 

I believe the dot syntax including optional quotes (my vote for \" instead of ' (or both)) is the way to go. 

Also a good addition could be a way to add scripts in line to the json file as well, as you can use sed or any other scripting tools to pass the entire json in one go without touching any files. I have 0 knowledge on JSX, but I don't think nesting is that bad, even if there was any other API methods.

Anyway, the solution above should work *ok* for other people who arrive here with the same issue if the dot syntax is not implemented yet, and depending on my priorities I might help implementing it as well.

**Comment by mujdatcicek** [comment]
Hello everybody. I'm facing same issue at now :)
I need to change the "Skin_Color" property, but i didn't find any solution for it.



<img width="474" alt="Ekran Resmi 2019-06-16 02 41 52" src="https://user-images.githubusercontent.com/7440211/59557356-6fa45e00-8fe0-11e9-84d4-f4e8152f2913.png">

**Comment by inlife** [comment]
@emiliobool @mujdatcicek im going to push a feature that allows usage of dot-styled syntax for property definitions soon, hope that will help

also, regarding this:
>Also a good addition could be a way to add scripts in line to the json file as well, as you can use sed or any other scripting tools to pass the entire json in one go without touching any files. I have 0 knowledge on JSX, but I don't think nesting is that bad, even if there was any other API methods.

Did you know instead of the file:// protocol you can use data:// protocol to directly store the values inside the json job. Details: https://github.com/inlife/nexrender#protocols

**Comment by inlife** [comment]
I've pushed a new build, `v1.5.0-alpha.0`
could you guys please try it out, to see if it works as you expect it to

You can use either dot (`.`), or arrow (`->`) for separation of sub-properties.

**Comment by emiliobool** [comment]
@inlife thanks that's awesome! it actually crossed my mind earlier today that I saw a data protocol but I wasn't sure I wanted to base64 encode, good thing we can use plain text too. But I guess even base64 is fine if I use the node.js api from a script.

**Comment by mujdatcicek** [comment]
@inlife thank you very much, now its working.

But there is a bug in there 
`property` variable should be change with `iterator`

scripts.js
`iterator.setValue($value);`

**Comment by inlife** [comment]
oh ye, it is, gonna push a fix

**Comment by inlife** [comment]
pushed w/ `v1.5.0-alpha.2`

**Comment by emiliobool** [comment]
@inlife I tried this today and it seems to work, I'm not sure about the alpha.2 not sure if the .1 version on npm is the one you meant but I didn't see any tag on github or npm for .2, anyway the latest version on npm worked fine for my property "Effects.BorderColor.Color"

I think with this change this issue is solved, and it will probably need a doc entry to specify how to change deep properties. Also using a control layer to specify all their "input" properties is probably the best approach/practice here, so recommending that would probably help some people too.

Thank you so much for the hard work!

**Comment by inlife** [comment]
Very good!
Yes, I will push an update with changes to doc, and promote it to full release.

>Also using a control layer to specify all their "input" properties is probably the best approach/practice here, so recommending that would probably help some people too.

Not sure what you mean by "control layer", could you explain more?

**Comment by emiliobool** [comment]
@inlife I mean just like in mujdatcicek's screenshot where he has a null object with custom controls. That way you swap the controls' colors/values from nexrender but you reference the control values everywhere else in your composition. That means easily exposing all modifiable values in a single place. I mean my suggestion is mostly showing and promoting that specific use case where instead of trying to modify lets say a style border color directly they can reference a control value using "Effects.ControlName.property" <-- I believe this string/property path name is what most people would be looking for

**Comment by inlife** [comment]
@emiliobool oh, I see. I feel like I don't have enough experience in this particular area.

Could you please check/validate new changes to the readme, if I provided the right information:
https://github.com/inlife/nexrender/commit/a2d7acc3930b46a9be267ee8f7f13149d6668c6a?diff=unified&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

And also, maybe if I missed something, especially in connection to your last message. If you notice something - I would be super grateful for either a pull request or a direct comment right here with instructions on what to change.

Cheers!

**Comment by emiliobool** [comment]
@inlife Yeah I think what you included should be self explanatory but:

```
 {
            "type": "data",
            "layerName": "background",
            "property": "Effect.BorderColor.Border",
            "value": [1, 0, 0]
        },
``` 

did you mean Effect.BorderColor.Color ? or is the Border property a real property? if it is a typo I would suggest changing it to "Effects.Skin_Color.Color" so it correlates with the image/text that comes before it. Other than that I think it is enough for people to understand it.

**Comment by inlife** [comment]
Oh yes, seems like I made a typo there. Great, thank you!

**Comment by inlife** [comment]
closing the issue since the feature is released

**Comment by FinnFrotscher** [comment]
this feature is so great... thanks!
