### ISSUE TITLE
Change codec and its options

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#118]
Is it possible to set codec and rendering options for that codec in template or in prerender script?

**Comment by inlife** [comment]
if you are referring to output template modules for after effects, yes, it can be set

most of the things related to settings/output templates and other things described there:
https://github.com/inlife/nexrender#details

>note: there is also link to adobe's documentation describing more

**Comment by franeko** [comment]
I see, thanks!

Vladyslav Hrytsenko <notifications@github.com> schrieb am Fr. 1. März 2019
um 19:22:

**Comment by franeko** [comment]
Would it be possible to load and use output modules from a file?

**Comment by inlife** [comment]
not sure, what do you mean?

**Comment by franeko** [comment]
Right now, I can create an output module and use it in a AE instance running on my PC, but when I want to use the same output module on another machine I have to manually go there and import it. 

Would it be possible to import output modules somewhere, eg. in a prerender script?

**Comment by inlife** [comment]
That is a good idea, however
I'm just worried about a potential possible collision of output module settings
particularly in case of let's say 2 running nexrender workers on the same machine attempt to replace a file that contains output module settings.

Also probably it is a good idea to revert to original file after rendering has finished, but again, what if the process was killed and auto-revert didn't happen.

The best case, probably, would be to add a custom entry to an output module settings, so it would replicate the one used in after effects.
Or even better, add an ability to directly set those settings from json job.settings. However, I'm not sure that the format of those settings is reversed since if I remember correctly it was a binary buffer.

**Comment by franeko** [comment]
Ok, I see that those issues might be too complicated to resolve properly. 

I am still interested how that might be done for my own purpose. Are output modules just some file in AE that I can just replace? Where can I find it?

**Comment by inlife** [comment]
On windows:
```
%appdata%/Adobe/After Effects/$VERSION/Adobe After Effects $VERSION Prefs-indep-output.txt
```

**Comment by franeko** [comment]
Thanks! I will look into what can be done there. If I come up with a
solution that would solve issues raised by you I will post here. For now I
think you can safely close this issue.

Vladyslav Hrytsenko <notifications@github.com> schrieb am Di. 19. März 2019
um 14:52:

**Comment by inlife** [comment]
thank you!
