### ISSUE TITLE
[Question] Adobe After Effects License for using NexRender in a SAAS

### ISSUE THREAD

**Issue by IICommitII** [inlife/nexrender#127]
Hey,

This is excellent, thanks for creating this. 

This is not an issue or a bug but just a question that has been really confusing me for past few days. I would really appreciate any help on this. 

I wanted to know what is the licensing situation from Adobe's end when using nexrender and after effects for a saas app where users are able to input their own texts and images into a predefined after effects project file and get an output in mp4 format after rendering the project via After Effects on the server.

How are you guys able to get a license that satisfies this use case? I tried to find such a license but couldn't get one so I am curious how is nexrender being used? That is, with what Adobe license? 

I am mainly concerned because if I use a normal After Effect's license to install AE on our servers, launch the app to 1000s of users and later found out that AE is trying to block us from using AE because it does not permit such use case? 

So, anyone who has any information about this, I would really appreciate your response on this.

Thank for reading!

**Comment by inlife** [comment]
Hello, Thank you!

That is indeed a very interesting question. The first thing that I worth mentioning, is that nexrender is not affiliated with Adobe or Adobe After Effects in any way, that also includes licensing. The product itself (nexrender) doesn't use any licenses from After Effects, since it is a separate product.

Regarding the licenses for After Effects, there is an option to rely on non-royalty bearing mode:
* https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html#segment_settings
* https://blogs.adobe.com/creativecloud/installing-after-effects-cc-render-engines-with-adobe-creative-cloud/
* https://blogs.adobe.com/creativecloud/codecs-and-the-render-engine-in-after-effects-cs6/

**Comment by inlife** [comment]
Hey @IICommitII, was this information enough, do you still have any questions related to this issue?
