### ISSUE TITLE
AE license required?

### ISSUE THREAD

**Issue by adanielyan** [inlife/nexrender#133]
In the documentation you say that nexrender does not require licenses for Adobe After Effects on any worker machine. However later in **nexrender-worker** section you list license/trial as a requirement:

> **Requirements:**
> Installed licensed/trial version of Adobe After Effects

Can you please clarify why license/trial is required?

**Comment by inlife** [comment]
Hello,

That specific part "licensed/trial" means, "either licensed or trial" version.
Meaning, In case you already have a licensed version, you can use it, to render otherwise you can install a trial version of AE, and the CLI renderer will be able to use it without need activate it.

Hope that clears stuff a bit!

**Comment by adanielyan** [comment]
Thank you for clarifying, Vladyslav. So, will the expired trial be sufficient or should I have an active one?

**Comment by inlife** [comment]
Well, for creating the initial project template (inside an After Effects GUI) you would need to have a licensed (or temp trial) version. However, for the actual GUI-less rendering just a trial should work fine without any problems.

**Comment by adanielyan** [comment]
Sure, I understand that. But the worker may be on a different machine, not the one where the project was created.

**Comment by inlife** [comment]
And that is ok; you will just need to install an After Effects there and leave it not activated.
That way it should work fine.

**Comment by adanielyan** [comment]
ok, thanks!
