### ISSUE TITLE
Run Nexrender without running aerender

### ISSUE THREAD

**Issue by nicolasguenther** [inlife/nexrender#139]
I'm interested in running nexrender without the actual rendering part. Just copying the after effects project, footage and generation of the jsx script would be enough. Is this possible?

**Comment by inlife** [comment]
Hello

That is an interesting question. I never thought about such a use case, and never expected anyone would try doing something like that! :D

However, I think there is a way on how to do it. Since you can set up the path to the aerender(.exe) binary manually (`--binary` flag), you can try creating a "mock" bin file and providing it as a forced path for the worker (after the initial patch for AE has been successfully installed).

That will result in nexrender launching your "mocked" version of the render file, and pretty much, doing nothing on the render step.

**Comment by nicolasguenther** [comment]
Thanks! I tried your proposed workaround and it works fine. When i run it without rendering this way and with --skip-cleanup and custom --workpath directory it still creates a random named subdirectory in my workpath. Is this intended behaviour? This makes it difficult to locate the copied after effects project programmatically.

**Comment by inlife** [comment]
Yes, that is intended behavior, since it was developed with a possibility of rendering multiple jobs at the same time, so it places the assets into a `job.id` folder inside of the workdir.

Since you are using such a custom approach you can add an additional post-rendering action that will do some stuff for your after the mock has finished, including launching your custom code or other application. And from that action you can have access to pretty much any entry to the job description, including the current location, the job id and all the asset files.

https://github.com/inlife/nexrender#custom-actions

And you can check out `action-copy` as an example: https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-copy

**Comment by inlife** [comment]
Hey @nicolasguenther, may I ask, what is actually the concept behind your use case?
How are you using nexrender without actually rendering?

I'm quite curious to know :)

**Comment by nicolasguenther** [comment]
The idea was to use custom scripts to split the rendering into multiple jobs and combine them again afterwards to utilize mutiple cpu's/multiple machines.
