### ISSUE TITLE
How to use the data protocol?

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#183]
In another thread I saw @inlife make this remark:

> Did you know instead of the file:// protocol you can use data:// protocol to directly store the values inside the json job. Details: https://github.com/inlife/nexrender#protocols

It sounds really interesting and useful, but the text behind the link for details only describes how to declare such data.
Does anybody have an example of how to use this feature?

**Comment by inlife** [comment]
Hello @brassel 

There is info on Wikipedia page on how to use the data based URI scheme: https://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by brassel** [comment]
Hi @inlife, thanks for the fast feedback! Yes, getting data into base64 encoding and such would be a requirement to use the data protocol. But what can I do with the data inside a nexrender project? Do you have an example where you made good use of it? Can i, e.g., access this from a script which is added to the job file?

**Comment by inlife** [comment]
Oh, I see what you mean.
Well, for example, a possible use-case for that might be, instead of relying on the file with an image to replace in your .aep project at render time, you can embed it directly into the json job file. Same applies for .aep project. Theoretically, you could just end up with a fully self-contained json file, without any external downloadable resources.

**Comment by brassel** [comment]
Ok, I get it, thanks!
