### ISSUE TITLE
Render Farm

### ISSUE THREAD

**Issue by BasicWatermelon** [inlife/nexrender#191]
Your main documentation quotes "farm" capabilities. I was wondering how this is achieved as being able to render a single project on multiple machines would be incredibly useful for me.

![15633127407](https://user-images.githubusercontent.com/37552537/61331368-c12b4d00-a819-11e9-8351-fe1ba6cadc95.png)

I have my nexrender-server set up and that's quietly chugging along in the background
![15633128554](https://user-images.githubusercontent.com/37552537/61331440-ecae3780-a819-11e9-8ce1-aa10715a6b30.png)

I'm assuming there's a few extra lines of code I have to include or something to get the workers configured correctly so they render 1 project at once.

Cheers,
Nathan

**Comment by inlife** [comment]
Hello @BasicWatermelon 

So, to render a single project on multiple machines (or on the same machine), currently, you need to do a bit of manual magic:

1. You will need to create your job and then copy it as many times as many workers you want to render your project simultaneously. So let's say you created a job description with all instructions ofr your project, then you copied it 3 times, so now you have 4 job json files.

2. Then you edit each one of them so that they would have `job.settings.frameStart` and `job.settings.frameEnd` set up and correspond to the number of frames you would like to render.

So for example, your total project time is 10 minutes (expected rendered video length), and your target FPS is 30, and you have 4 parts to divide to, that means that each part would need to render 2.5 minutes worth of footage. And little bit of math: 2.5min == 150sec * 30fps = 4500 frames for each worker.

So you set up your jobs like this:
1st job: start: 0, finish: 4499
2nd job: start: 4500, finish: 8999
3rd job: start: 9000, finish: 13499
4th job: start: 13500, finish: 17999 // the later one can be skipped since we already know it will be the end of the composition

3. You post your projects to the nexrender-server

4. You gather the results into a folder on a single machine (using shared folders, dropbox, rsync or any other viable way)

5. You glue the parts together with a tool of your choosing (Depending on the format of your rendering output it might be different, 4 video files, or 4 sets of images and soundtrack)

As you can see the process isn't the most straightforward at the moment. However, I'm planning to actually automate most of it, and roll it out as a feature later on.

**Comment by BasicWatermelon** [comment]
Oh cool, I was expecting it to be much more convoluted than that, cheers.
Had one other question, how do you specify a work path when using the server/worker stuff?

**Comment by inlife** [comment]
I suppose you mean the working directory?
Quite simply you just provide -w (or --workpath) argument to the worker.

(You can get more details in the --help menu)
![image](https://user-images.githubusercontent.com/2182108/61361950-071ff980-a88a-11e9-9c01-3017799ed0c5.png)

**Comment by BasicWatermelon** [comment]
Oh derrr, silly me. Thanks a lot

**Comment by inlife** [comment]
you are welcome! :)

**Comment by BasicWatermelon** [comment]
Hey, managed to get this all working. An interesting thing I've noticed is both the workers and server seems to get a little stuck sometimes and I have to Ctrl-C on them to get them to actually update. Any knowledge of this and how to prevent it or am I just doing something weirdly?

Thanks

**Comment by inlife** [comment]
Actually not sure, never had this happen. What are the conditions of reproducing this behavior? How much time it usually takes before it happens, maybe something else?
Which are the platforms it happens on, and are those binary versions or ones from npm?

**Comment by BasicWatermelon** [comment]
I'll see if I can reproduce it for you, it's super weird so I'm not surprised you've not encountered it. NPM packages running on Windows.

**Comment by BasicWatermelon** [comment]
https://drive.google.com/open?id=1j_QftiYG3-MFOec7tH8jCHEu2D93vw2L

Key moments: 
0:35
2:25

**Comment by BasicWatermelon** [comment]
As you can see it just sorta... Happens. No clue why whatsoever.

**Comment by inlife** [comment]
Oh, I see now. It seems to me that is cursor selection problem on windows in the terminal, isn't it?
If we are talking about the same thing, that always happens to any cli process on windows.

For example, try running `tree` in cmd.exe, and then move the mouse and select part of the console.
To unselect you would just press any key, and the program continues.

**Comment by BasicWatermelon** [comment]
Oooh, interesting. I'll keep it in mind, cheers.

**Comment by inlife** [comment]
Actually, @BasicWatermelon while we are there, I wanted to ask you. Since you are using multi-image rendering, how do you handle the sound? Is it rendered separately via some different audio-only outputModule, and then you glue them together? If so, which tools do you use for that?
Thanks

**Comment by johnrico2000** [comment]
> As you can see the process isn't the most straightforward at the moment. However, I'm planning to actually automate most of it, and roll it out as a feature later on.

Hi, are you still planning on bringing this feature to nexrender? It would come in quite handy, I must say. ;-)

**Comment by inlife** [comment]
I haven't had a chance to do actual work on it, so I would say its still in the research/planning phase.
