### ISSUE TITLE
how to use rendering cluster

### ISSUE THREAD

**Issue by fyshequ** [inlife/nexrender#192]
I have 10 servers, my project is about short videos. Today the rendering time is 50 seconds. But the idea is to render under 10s. So, I'm trying to find the best way to do it.

**Comment by inlife** [comment]
Hello @fyshequ 

If projects are really small, and you have a lot of videos, I'd suggest just pushing all of those videos to the `nexrender-server` and they would be divided by `nexrender-worker` and rendered simultaneously. 

So in case 10 videos you need to render at once, rendering all videos would take roughly 50 seconds, instead of ~10 seconds each accounting up to ~100 seconds total.

And also I suggest you read my comment in the previous issue: #191 

Cheers!
