### ISSUE TITLE
Cloud Rendering Setup

### ISSUE THREAD

**Issue by mackenly** [inlife/nexrender#200]
First of all love this project and can't wait to try it out! What would be the best setup for cloud rendering on g cloud or aws? I've checked on some of the prices and it appears that the prices would add up quickly. What would be the best option while keeping prices reasonable? How high of a spec should I consider?

Thank you!

**Comment by inlife** [comment]
Hey @mackenly!

I would assume from one to a couple of machines running windows server 2019 on either of those two. I know about successful cases on both platforms.

However, everything depends on your needs, and you always can boot up and stop additional machines.

Regarding performance, this is more question to the After Effects software, since it is the one doing the main rendering process.

**Comment by mackenly** [comment]
Awesome! Would there be anything to prevent me from running a few workers myself and just running one or so on the cloud as back ups?

**Comment by inlife** [comment]
Nope, it should work fine.

**Comment by mackenly** [comment]
@inlife One more question haha, what would be the recommended spec for the master and worker nodes?

**Comment by inlife** [comment]
well, server (master) doesn't need much; neither memory nor CPU, so the smallest sized VM/instance should be more than enough. I think it should work fine on machines with above than 100mb of ram.

and regarding workers - as I mentioned before, that is totally up to After Effects. You would need to check specs required for After Effects to see to tell what you need. the worker itself also doesn't add any additional requirements; compared to AE it should be like a drop in the ocean
