### ISSUE TITLE
is it possible to change temp folder location for nexrender ?

### ISSUE THREAD

**Issue by whatneuron** [inlife/nexrender#217]
I am using SSD (128GB) and for some reason 4 minutes video generated is going well above 35GB (still counting...)

Can I change temp location of nexrender to another drive where I have more space ?

OR

Can I do something to generate videos with lower space taken 35GB sounds like a disaster.

Thanks

**Comment by inlife** [comment]
Yes, you can change the temp location, if you are using binaries just provide `--workpath` argument with a proper path to a custom temporary folder. Type `--help` for more info.

Since aerender doesn't offer too much choice, the default lossless export module that renders avi/mov with big file sizes is unfortunately what we need to live with, and there is no other way around it (at least to my knowledge).
