### ISSUE TITLE
Is it possible to set the FTP upload destination?

### ISSUE THREAD

**Issue by chrstnsmthng** [inlife/nexrender#219]
Describe your question, attach logs, images or anything that might help to better understand it.
Everytime I use the action-upload with a file, the filename is the path from the computer it's rendered on. It is possible to change the folder it's uploaded to in the post-render object?

**Comment by inlife** [comment]
I guess the best answer can be found in the docs regarding the ftp module.
https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-ftp

Since any params passed in the object will be directly passed into the node-ftp, it can be used to put some additional options. I'm assuming there must be a way to provide a target upload directory, or maybe some other way of achieving that.

**Comment by inlife** [comment]
Actually seems like from the `.put` description, the src field can be used to put file in the specific destination, however, the way it is used in our ftp and upload modules doesn't allow it to be provided from outside, that seems to be a bug.

**Comment by inlife** [comment]
I guess the best way to solve this would be adding and "output" field to the action-upload settings, that would be used to both form the key for AWS S3 module (unless there is already a "key" field defined in params), and a destination for FTP module.

**Comment by inlife** [comment]
Added ability to set FTP output name, right in the `params` object in https://github.com/inlife/nexrender/commit/5e9ac8e78e42f02e4685122388215c0731b7d120.
And updated example: https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-ftp#usage-upload
