### ISSUE TITLE
[action-encode] Error processing input

### ISSUE THREAD

**Issue by vizcosity** [inlife/nexrender#221]
**Describe the bug**
Recently I have been experiencing errors trying to use action-encode as a postrender module. Using the default 'mp4' preset, I get the following:

[DzWWgbOzBse7PreKsovn5] [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fde43000000] moov atom not found

[DzWWgbOzBse7PreKsovn5] /var/folders/_q/7xhh3jm14hx7p5ypx3n8drg00000gn/T/nexrender/DzWWgbOzBse7PreKsovn5/result.mov: Invalid data found when processing input

This type of error seems to appear when ffmpeg is called on corrupted / partially downloaded source files. I suspect that the post-render module may be called before the video file is completely finished being rendered / written to file. 

Adding a short timeout of 5s before action-encode spawns the ffmpeg process seems to resolve the issue :)

**Information about environment**
* nexrender 1.5.7 & @nexrender/action-encode 1.5.8
* Mac

**Comment by inlife** [comment]
I see, yes I think I've encountered similar issue somewhere before. The delay even tho it would work I think wouldn't be the safest solution, since I believe in some cases it might take a random amount of time.

The best solution I guess would be finding a way to definitely say that a specific rendering job has finished.
