### ISSUE TITLE
Render Percentage Calculation 

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#257]
Hi
We have followed the following work procedure for rendering videos using nexrender. Below are the details which we followed.    
* We have hit the API server for rendering the video
* The API server hit the request to our nexrender server for break-in pool and connection worker generated wait for the response of worker
* the worker processed the JOB and generate the percentage of work based on the frameset of video and respond to the server after complete the job (100%)
 Requirement:
How can we communicate the frameset of the percentage of the worker during the processing time with my API server and please also provide the idea on how to "Calculate the Render percentage" and what steps shall we follow.

**Comment by inlife** [comment]
Hello @pixelfactorydevelopmentteam 

Ideally, all you technically need is just a way to post back the rendering progress to the API server from the worker, since worker already does process calculation internally.

I can see 2 possible ways:
1. Hosting both server and worker as a nodejs programmable modules inside your own nodejs processes, and using console logging api of the worker to track the changes (this way is a bit hacky)
2. Forking nexrender and adding such feature (and possibly even creating pull request to this repo, I think a lot of users might appreciate something like this)

Hope that helps!

**Comment by pixelfactorydevelopmentteam** [comment]
@inlife Thank:)
I'm testing that.
