### ISSUE TITLE
Passing arguments to jsx script

### ISSUE THREAD

**Issue by ahardworker** [inlife/nexrender#259]
**Is your feature request related to a problem? Please describe.**
It seems that this library doesn't support passing arguments to a JSX script. It would be really handy.

**Describe the solution you'd like**
It would be great if there was a way to send an array of parameters in the JSON object.

**Describe alternatives you've considered**
The only solution is to create a file with the parameters and read it in the script, however that is a bit of a hassle since it would limit the rendering to one item a time.

**Comment by ahardworker** [comment]
Nvm, you can easily pass parameters using assets.

**Comment by dukuo** [comment]
@ahardworker pass parameters using assets to the script or to the global operation? If it's the former, what's the syntax for it?

**Comment by danielgwilson** [comment]
I'd still like this as a feature (unless passing params with assets is actually easier than I realize—not clear atm).

**Comment by dukuo** [comment]
Apparently the current solution, which was briefly discussed on discord  ([invite](https://discord.gg/S2JtRcB)) is to cook a script with the correct parameters, encode it in base64 using the `data://` protocol and pass it to the JSON file as an asset.

**Comment by danielgwilson** [comment]
> So one solution off the top of my head could be to enhance the `data` asset with a parameter parsing/injection feature, which would in turn require to have a different syntax of the script code to handle blank/placeholder parameters maybe?

I think this idea is in the right direction; I've found the following approach most convenient:

```typescript
{
    type: "data",
    property: "startTime",
    expression: `
      var comp;
      for (var i = 1; i <= app.project.numItems; i++) {
          if ((app.project.item(i) instanceof CompItem) && (app.project.item(i).name === "${compName}")) {
              comp = app.project.item(i);
              break;
          }
      }
      comp.duration = comp.layer(1).outPoint;
      layer.startTime;
    `
  }
```

Basically, this uses a data/expression asset to execute a script with injected parameters. The final line of the script sets the layer property `startTime` (arbitrary) to the same value. This allows the opportunity to run an arbitrary script defined in code rather than a file.

If this approach isn't too crazy, it would be nice to have a `{ type: "script", expression: "..." }` option or similar which didn't require dummy values for `layerIndex` / `layerName` and `property`.

**Comment by dukuo** [comment]
My PR [307](https://github.com/inlife/nexrender/pull/307) has an implementation of dynamic variables! Try it out @danielgwilson and let me know if it's of any use to your case.
