### ISSUE TITLE
Replacing requireg with an alternative

### ISSUE THREAD

**Issue by zuntah** [inlife/nexrender#265]
Hi,
I would like to run nexrender-worker from the source code, and it's very problematic.

### **Modules I need to use:**
1. worker
2. action-encode
3. action-upload
4. provider-ftp

### **The problem:**
The file **actions.js** in the **nexrender-core** package and the file **index.js** in the **action-upload** package.

They use the function "requireg" in order to load the relevant modules (Post-Render / Provider).
This means that it doesn't matter if I change the source code of "action-upload" package for example because in the end the post-module will be loaded from the global node_modules dirrectory.

This means that in order to optimize the source code for my special needs, I need to create a pull request, the pull request needs to be approved and the npm repository should be updated with the new source.

### **Temporary Fix:**
I changed it manually to use the function "require" instead of "requireg".
The problem had been fixed, But I wanna discuss with you here about a better long term solution.
In addition, I think there should be a section that explains how to run the project from source code with all the relevant modules.

What do you think?

Thanks,
Jonathan.

**Comment by inlife** [comment]
Hello @zuntah 

That is actually quite bad, since my understanding was that requireg will resolve it fine if you are trying to use a local dependency (at least it worked that way in my case), unless it is not a local dependency?

I was considering replacing a requireg with something lighter, and more configurable in some way. Not sure yet how to approach it. You rasing quite a good point, however, and quite complex as well.
