### ISSUE TITLE
No error when render failed

### ISSUE THREAD

**Issue by AntonPrusov** [inlife/nexrender#270]
I have been using Nexrender for a month and I have a problem. When an error occurs during video rendering, the process continues, postrender actions are applied. I got error only in postrender because of no result file to work with. I can get error just from log file in temp folder. A looked to source code of render task and saw here 
`
if (code !== 0 && settings.stopOnError) {
                return reject(new Error(outputStr || 'aerender.exe failed to render the output into the file due to an unknown reason'));
            }
`
but no error in console and promise is resolved.

What can be the problem and how can I get aerender error string like the one in log file (example: "aerender ERROR: No comp was found with the given name.")

**Comment by inlife** [comment]
Hello

There are currently indeed some issues with some of the error handling coming out from aerender process. I wanted to create a proper solution for that but had no time yet.

For the specific error you mentioned, the reason is that aerender cannot find a composition in the AEP project file you provided. Try to validate that both names in the job.template, and for each job.asset that might be using composition instruction has a proper existing in AEP file composition name.

Cheers!

**Comment by AntonPrusov** [comment]
I understand what this error mean, but the question was how to get error string in js.
