### ISSUE TITLE
how to use nexrender on aws ec2 windows server?

### ISSUE THREAD

**Issue by sitestrokes** [inlife/nexrender#274]
I installed adobe after effects in windows instance server.
my adobe after effects installation in windows present in c:/program files/Adobe...

now I want to use those files globally
how can I use this?

My Project is hosted on another server and they need to call one file in windows instance,

how to access publicly because all are in windows ec2 server
C:/nexrender_cli/nexrender-cli-win64.exe  
C:/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe

above files are present in windows instance in RDP and i am unable to access those files .and in nexrender i need to access those files.

Please help me to resolve my issue.
Thanks

**Comment by inlife** [comment]
First, make sure that both nexrender and After Effects will be running on the same machine.
Second, try to carefully read the https://github.com/inlife/nexrender#network-rendering section of the readme. Since CLI version is not the best choice for this specific kind of setup I would say.

Regarding file access for nexrender, if the files are accessible as network drives, there might be differences in how they should be referred to. As alternatives, you can also try one of the protocols for file delivery shown in the https://github.com/inlife/nexrender#protocols

**Comment by sitestrokes** [comment]
hello,

i am able to rendered video using nexrender binary file.
i want to display rendering progress in percentage but i dont have any idea about that?

is there any possible way to show rendering progress in percentage?

thanks.

**Comment by inlife** [comment]
Where do you wanna display it, inside a video?

**Comment by sitestrokes** [comment]
Hello,
I want to display rendering progress in percentage in the outside video.
when I click on to create video then I execute shell_exec command and rendering process is start.but in that process I want to display rendering progress percentage so I can understand the status of rendring and remaining time to complete video.

**Comment by inlife** [comment]
Automatic progress syncing to api server was added in commit https://github.com/inlife/nexrender/commit/8b2dc86518c2870b0c6851e375eb9ea288372189
I think that can be used to achieve what you want
