### ISSUE TITLE
Cineware support (Cinema4D)

### ISSUE THREAD

**Issue by johkon** [inlife/nexrender#281]
Hello everyone,

i have tried rendering a comp with a .c4d layer in it, but only get a black 1-frame video file. Is Cineware supported at all or is there no way to get that working?
My setup and template work, i have renderd out another comp in the same File.

Nexrender is great either way, thanks for the great work :)

**Comment by inlife** [comment]
Hello @johkon 

I believe this is the first time anyone asked about Cinema4D support. And honestly, I have no idea. Since I know that some plugins working fine with nexrender, I can assume that this might be Cinema4D specific issue. 

Are there any messages in the render log coming from After Effects?
Maybe we can try to understand what is going wrong and fix it.

Cheers!

**Comment by johkon** [comment]
Hi @inlife, thanks for the reply.
i have built a simple version of my template. 
[Templates.zip](https://github.com/inlife/nexrender/files/3908068/Templates.zip
what i`m trying to do is to replace a texture on a 3D object, by using the same jpg on a After Effects layer. I thought, that this should work since Cineware and Cinema4D Lite are stock parts of After Effects. However, even if the c4d-Layer has no textures, it doesn´t work.

Here is my CMD Log of the rendering:
![CMD](https://user-images.githubusercontent.com/57528885/69912652-a3f3c580-142c-11ea-98a3-b02e477011d0.jpg)

Thanks so much for taking time to look into this :)

**Comment by johkon** [comment]
Ok, it works now. :)
i guess its advisable to keep the directories of your templates the same on all machines. Just to keep absolut paths correct.

**Comment by inlife** [comment]
Oh, I see. Glad to hear that! :)
