### ISSUE TITLE
Nexrender-Server: job is being taken many times by multiple nexrender-workers

### ISSUE THREAD

**Issue by zuntah** [inlife/nexrender#293]
**Describe the bug**
I have 8 workers that are connected to the same nexrender-server.
Once a job is created, 3 workers took it and render it at the same time instead of 1.

**Information about environment**
* Which version of nexrender are you using? **Latest**
* What kind of the setup do you have? **Nexrender-server - ubuntu, 8 Nexrender-workers Windows 2018.**
* Are you using pre-built binaries or globally installed npm packages? **NO**

**Expected behavior**
Once a worker is getting the job, The next time jobs are being fetched by the worker, this particular job should not exist.

**Screenshots**
![Screen Shot 2020-01-05 at 16 33 53](https://user-images.githubusercontent.com/2213214/71781627-9c01e500-2fd9-11ea-83ed-54d7a9c06c81.png)

**Comment by inlife** [comment]
Apparently a kind of "data race" is happening. We need to rethink the way jobs are distributed. If I remember correctly currently jobs are selected on the worker side, which is the root of the issue, we would probably need to move selection process to the server.

**Comment by zuntah** [comment]
I saw that at the nexrender-worker in the file index.js, you were trying to update the job state multiple times.
Maybe a good solution is to move
`await client.updateJob(job.uid, job)`
into the nextJob function right after picking up a random job, inside this if:
`if (queued.length > 0) {
           return queued[Math.floor(Math.random() * queued.length)];
}`

Jonathan.

**Comment by inlife** [comment]
I believe if that even improves the situation a bit, it would still not fix the issue fully. Since there is some time while data is being sent, parsed and received. And there is a chance that all workers would ask for a job at exact same time, and they all would receive a list of jobs, and even at random, they would select the same job.

**Comment by johnrico2000** [comment]
I'm using your project a lot lately since it will probably become some integral part of a startup project I'm trying to get going. I think I noticed the race condition, too, a few times. I support your idea to move the job distribution to the server. The server could ask which workers are free at the moment and then select one to assign the job to. I think that is what you had in mind, right?
Thank you for the work that you have already put into this neat tool. :-)

Frank

**Comment by inlife** [comment]
Pushed a commit that should fix that https://github.com/inlife/nexrender/commit/8e152a4784fd264703c32c47a04ae1297f011482

Going to be delivered with the next release
