### ISSUE TITLE
Transitions between after effect projects

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#354]
Can nexrender handle transitions between multiple after effect projects?

**Comment by inlife** [comment]
Hey,

Not sure how is that possible. Can it be done in after effects?

**Comment by matteoraggi** [comment]
Yes for sure

Il mar 7 apr 2020, 07:10 Vladyslav Hrytsenko <notifications@github.com> ha
scritto:

**Comment by inlife** [comment]
Could you please show an example of such project in aep?

**Comment by matteoraggi** [comment]
her many demo https://www.youtube.com/watch?v=iiy2oX4GFCA&list=PLBfZVEoK7SBhnyqYZupdcmKS6RNNc5WIW

**Comment by TimP4w** [comment]
@matteoraggi The one you mentiones are normal transitions effect between images. 
If you prepare an .aep with those, then you can replace the various images using nexrender.

**Comment by matteoraggi** [comment]
yes I just would like to do it between multiple dynamic (the number of the videos is dynamic) videos instead to use it between images.

**Comment by TimP4w** [comment]
@matteoraggi I'm not sure it's possible to specify a variable amount of videos to be added together (I'm not an AE expert). But what you can do is to create various templates which accepts two videos and puts a transition between them. Then let's assume you have 3 videos and call them A, B and C: you could render the first two with the first transition you choose, then use the result of that and render it with the third video and another transition. 

A + B -> AB
AB + C -> ABC
...

This approach could be used by any n amount of videos.

Otherwise you can have a look here: http://docs.aenhancers.com/ and maybe find some useful methods and write a custom script to achieve what you need.
