### ISSUE TITLE
Add Job asset type: Json

### ISSUE THREAD

**Issue by Marcuzzz** [inlife/nexrender#366]
Could you please add:
to packages/nexrender-types/job.js
```
        switch (asset.type) {
            case 'image':
            case 'audio':
            case 'video':
// case json:
            case 'json':
```
And or explain how to build nexrender-cli
I've tried downloading the source-code and run npm install 
but than it  becomes complicated 

```
Lifecycle scripts included in nexrender:
  start
    npm run bootstrap
  publish
    lerna publish
  test
    lerna bootstrap && node test.js
```
Not sure how to proceed.. 

I did saw the reply on this:
https://github.com/inlife/nexrender/issues/130

But isn't as simple just to add the above switch case?

**Comment by inlife** [comment]
Hey there @Marcuzzz 

I added new asset type `static` in the latest version `1.14.0`, please check it out and tell me what you think

**Comment by Marcuzzz** [comment]
Cool works, thx a lot!!!

**Comment by phileastv** [comment]
For future people watching this issue, **I've found a pretty nice hack** !

The static asset data type is pretty cool ! However, **it does not seem to import the JSON file into the actual After Effect project**, but rather just copy it into the Nexrender project folder.

I have a project where I have a lot of text contained into a JSON file to replace in my rendered videos, and would prefer to replace the single JSON footage file in the AE project _(and because all my text layers are linked to this footage in my template, replacing all the text)_, rather than creating a lot of data assets elements for each text in the nexrender json task.

I've found that importing the JSON file as an `image` type file, **actually replaces the JSON footage in the AE project and all its contents** _(which is super, duper great as it changes all the text with only one asset type)_ !

```
{
          type: 'data',
          layerName: 'NOM',
          property: 'Source Text',
          expression: 'Test',
        },
```

The only issue with this has to do with the way After Effect supports this. Even if aerender should be headless, AE warns by this message that the JSON file has changed, and the render would not continue unless you click on "OK". Which is pretty dumb as it would be an incredible workflow.

![Capture d’écran 2020-12-22 à 22 54 29](https://user-images.githubusercontent.com/20335741/102936558-a9450780-44a8-11eb-8f4e-d64fa605c150.png)

[An issue request is already here](https://adobe-video.uservoice.com/forums/911311-after-effects/suggestions/34797730-ability-to-hide-json-warnings-when-structure-chang) to have the availability to hide this message.

Please, pleaaaaaase do not change this behaviour in nexrender (even if this is a little strange to consider a JSON file as an image asset type).

**Comment by inlife** [comment]
> Please, pleaaaaaase do not change this behaviour in nexrender (even if this is a little strange to consider a JSON file as an image asset type).

Haha, sure thing, we will try to keep this bug as a feature, no problemo! :D

P.S. I will think about adding a JSON asset type that would work more like an image type in the future.

**Comment by ghalehnoei** [comment]
> > Please, pleaaaaaase do not change this behaviour in nexrender (even if this is a little strange to consider a JSON file as an image asset type).
> 
> Haha, sure thing, we will try to keep this bug as a feature, no problemo! :D
> 
> P.S. I will think about adding a JSON asset type that would work more like an image type in the future.

Did you add JSON asset type?

**Comment by giuliobertolotti** [comment]
Totally looking forward to see this improvement, any update?
Could be a very game changer in how we use nexrender with template rendering. 
Thanks for all your work @inlife

**Comment by inlife** [comment]
Unfortunately, I do not think there was a chance to do that. But any suggested implementation or even pull requests are very welcome!

Stay strong! 🇺🇦
