### ISSUE TITLE
How to use base64 encoded image in a render?

### ISSUE THREAD

**Issue by lynchy-boop** [inlife/nexrender#391]
Hey how do i use base64 encoded images in a render?

**Error i get:**
`Error: After Effects error: File 9k= is not a valid file type for import.
aerender ERROR: Runtime error in After Effects.
aerender version 17.0.6x35
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched`

**Image asset:** 
`"type": "image", "composition": "productImage",
        "layerName": "product.png",
   "src": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4Qg+RXhpZgAATU0AKg....`

**Comment by inlife** [comment]
Hey

The way you showed it in your message, should be the correct way. However, as far as I can see it doesn't seem to work. Which version you tested this on?

Is there a chance to test it out on an older version? `1.15.*` or below should do.

**Comment by benjioh5** [comment]
@lynchy-boop @inlife I found reason. Aerender checks file extension and binary header of src. nexrender save these "data://" base64 packed file without file extenion (e.g. save png file without .png) on tmp rendering folder. So, aerender emits error about file extension.

So,
```
Error: After Effects error: File 9k= is not a valid file type for import.
```
is emitted by no file extension on tmp folder images.

The easiest way to solve this problem is add some file extention on "src".
```
src = src + ".mp4" // File 9k= -> 9k=.mp4
src = src + ".png" // File 9k= -> 9k=.png
```
would works find to me. But I think nexrender json parser sholud take care of file extention on `data://` format

**Comment by inlife** [comment]
That makes a lot of sense, @benjioh5 
Added a commit c5a8944 that should help with this!
