### ISSUE TITLE
Feature Request: Change Worker Allocation Algorithm: Use a FIFO Queue Algorithm. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [inlife/nexrender#410]
**Is your feature request related to a problem? Please describe.**

**Problem:** 

The nexrender server is allocating tasks to workers in unordered way. I allocated 20 jobs to 3 workers. A lot of times the latest/new jobs are getting fetched by workers first even when there are older jobs that are still in queue. 

**Possible Solution:**

I wanted to ask is it possible to use a pull based Messaging Queue (Redis/Kafka/Amazon SQS/RabbitMQ) instead a Database for storing the jobs allocated to nexrender-server?

**Comment by inlife** [comment]
Hey,

Just published `1.17.0`, changed default ordering to FIFO, and also added ability to define custom ordering for nexrender, check out readme page for server: https://github.com/inlife/nexrender/tree/master/packages/nexrender-server

Regarding the Messaging Queue, it is not possible to use those currently. Mainly because nexrender server has so tiny footprint, compared to those, that introducing even a single one to the project will require more stuff than the whole server currently has/uses.

As an alternative, I don't see a reason why an alternative nexrender server could not be created. A server that would operate using one or all of those message queues. Especially, since the nexrender server is just a tiny HTTP API server with a few methods.

**Comment by FRANK-AND-FREE** [comment]
Great to have the FIFO feature now. Thanks. I needed that, too, since I split video rendering into serveral nexrender jobs and oftentimes not all jobs for a video were rendered with priority, because new jobs that were added took priority over the first ones.

**Comment by ujjwalagrawal17** [comment]
Thanks @inlife . I will check it out.
