### ISSUE TITLE
cancel render

### ISSUE THREAD

**Issue by jonnymangothinkjam** [inlife/nexrender#421]
Is there a way to cancel a render?

once i've started a job, say i realise i've made a mistake, rather than have to wait for the render to finish is there a way to cancel/stop it?

**Comment by inlife** [comment]
Hey @jonnymangothinkjam 

The only way to stop a running job right now, that comes to my mind is to essentially kill a process that does the rendering.
Unfortunately, at this moment there are no other ways of doing that, since AE does not give us an API through which we could do that within aerender, as far as I know at least.

Cheers!

**Comment by olekristensen** [comment]
I'd like to be part of investigating this further, eg by finding a way of discovering the processes started by aerender (like aerendercore) and store them on the job, and adding a method on the job to kill the whole tree and do the cleanup.
Anyone with experience in this?
I've outlined a crude approach that we're using at DR in a discussion here:
https://github.com/inlife/nexrender/discussions/739
