### ISSUE TITLE
Can't render .mov file to mp4

### ISSUE THREAD

**Issue by Binipro** [inlife/nexrender#426]
Hi @inlife 

I am trying to render ".mov" file and then convert it to "mp4" using the encode module, but from the aerender spawn log it seems that it always passing the format ".avi" to the -output parameter (screenshot below) .

![image](https://user-images.githubusercontent.com/10253396/86801380-3966d000-c074-11ea-81c3-114bfa75e2fb.png)

 The encoder also looks for an input  result.avi instead of result.mov. 
![image](https://user-images.githubusercontent.com/10253396/86801463-50a5bd80-c074-11ea-8237-a2dda8b2ebe3.png)

The after effect log correctly shows the output module is a mov file. 
![image](https://user-images.githubusercontent.com/10253396/86801688-98c4e000-c074-11ea-8548-7d7560be8c13.png)

Is it supported by Nexrender to render .mov file? if yes, what am I missing?

**Comment by inlife** [comment]
The reason is simple, usually, there is mov on macOS, and avi on Windows. And nexrender automatically attempts to help people deal with those without any additional hustle.

What you can do, however, is to provide a custom outputExt for your job (`job.settings.outputExt`), with value of "mov". That should identify to nexrender that you know what are you doing in regards of the extension :D

**Comment by Binipro** [comment]
Thanks!
