### ISSUE TITLE
Is there any Possibility to Download/Install Plugins using Nexrender

### ISSUE THREAD

**Issue by darshak-gosar** [inlife/nexrender#464]
Hi @inlife ,
I was just wondering whether is there any possibility to download/install the plugin if we pass it in JSON like:
`Plugin: pluginName`
and It will download/install the plugin from specific location ?

Thanks :)

**Comment by inlife** [comment]
By "plugin" you mean After Effects plugin?
No, there is no such ability right now. Sounds like a nice feature tho.
Could you describe more how it would work, where would it download those, where would it place them and so on?

**Comment by MHanutko** [comment]
That would be a really cool feature actually.
+installing all needed fonts via nexrender as well.

Could be done via other workarounds, but an integrated feature would make sense.

**Comment by ReneVanV** [comment]
Is it possible to select a render plugin like GifGun to export the template I made? So instead of a normal render, using the gifgun render.

**Comment by iamkhalidbashir** [comment]
I mean downloading the plugin doesn't needed to be added into the nexrender app
we can download it manually
but using the plugin? there must be a way to achieve this on the current version of nexrender because we are using AI's aerender to render it, what if we place the plugin at appropriate position so aerender can pick it up while rendering the video?
Can we make the plugins work in that case ?

**Comment by inlife** [comment]
If plugins are properly configured and can be used from within aerender on all machines, nexrender should be able to use them without any problems as well. 👍
