### ISSUE TITLE
TypeError: micro(...).listen is not a function

### ISSUE THREAD

**Issue by devAkashmaurya** [inlife/nexrender#750]
I am getting this error again and again with this latest version of nexrender 1.39.5
I am trying to bring up the server 
![image](https://user-images.githubusercontent.com/86648774/180596645-7552d3ec-aaec-4237-99d2-b676171d1ddc.png)

**Comment by inlife** [comment]
Hey @devAkashmaurya 

How can I reproduce this error?

**Comment by vonstring** [comment]
I get this with a fresh install. Seems to be an issue with the latest version of Micro, because the issue disappears if I explicitly install micro@9.3.3.

**Comment by inlife** [comment]
Hey @vonstring @devAkashmaurya 

Thank you so much for that hint! The issue was indeed caused by `9.4.0` release of micro that had a breaking change and was not promoted to major release. I enforced the `9.3.x` as a requirement and published a new version `1.39.6`.

Please check it out and see if that works for you!

**Comment by vonstring** [comment]
Works a charm. Thanks @inlife !

**Comment by inlife** [comment]
Fantastic, thank you @vonstring !

**Comment by devAkashmaurya** [comment]
Yes... Really it is appreciating. Thanks for this info.

Akash Maurya
