### ISSUE TITLE
how to trim assets video with start point and end point with ffmpeg nexrender

### ISSUE THREAD

**Issue by nazemi0101** [inlife/nexrender#790]
We want to specify the start and end Point Range of the video so that NexRender using ffmeg, first cuts the user's video in the specified range and then replaces it with assets layes send 

assets": [
        {
            "src": "file:///d:/images/myimage.mp4",
            "type": "video",
            "layerName": "myvideo.mp4",
            "startPointTrim":1.05(milisecound),
            "endPointTrim":560(milisecound)
        }

**Comment by limzykenneth** [comment]
If I understand correctly, you want to trim the input video asset before it is used as an asset in the After Effects project render? 

That is certainly an interesting use case, I haven't tried something like this before but I think you can use the [nexrender-action-encode](https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode) action but instead of defining it in the postrender hook, you can define it in the prerender hook with specificed input and output location plus ffmpeg arguments about where to trim.

Let me know if any of that doesn't make sense, I'm interested in exploring this usage as well!
