### ISSUE TITLE
'rendering job' In what to do? 

### ISSUE THREAD

**Issue by youzhajun** [inlife/nexrender#807]
When rendering video on the ae graphical interface, it takes about 30 seconds. When using our script service to render, it takes about 2 minutes. In the 'rendering job' phase, it takes a long time. I want to know what configurations I missed or what can be optimized? thank you.

**Comment by limzykenneth** [comment]
The thing that's taking the most time is probably the start up, where rendering directly from AE doesn't require that because you have already opened AE, with Nexrender it will have to open AE before it can start rendering. Using the `reuse` option may help with this problem but it does not work in every case.

**Comment by youzhajun** [comment]
@limzykenneth  hello，'reuse'
Is this property set when starting parameters? Where can I get the configuration items of startup parameters? Thank you very much, my friend.

**Comment by limzykenneth** [comment]
`reuse` is defined [here](https://github.com/inlife/nexrender#information) and defaults to false.
