### ISSUE TITLE
API secret storage best practices

### ISSUE THREAD

**Issue by gdrtrts** [inlife/nexrender#851]
I was wondering what would be the best practice for securely storing API secrets using Nexrender server.

`const client = createClient({
    host: 'http://my.server.com:3050',
    secret: 'myapisecret',
})`

The scenario would be the following:
1. A user visits my custom web domain and is able the fill out details within an HTML form and presses submit.
2. After submitting, the render will start on my machine and the output file gets sent back to him afterward

Following the above scenario, what is the safest way to store the API secret? And let's say someone has access to my API secret, can he or she initiate renders from his machine to be completed on my machine indefinitely? And is the above scenario even possible with Nexrender server?

**Comment by limzykenneth** [comment]
The secret value should only be stored server side and never sent to the custom frontend, ie the custom web page should send the render request to some server on your backend (that possibly authenticate your user some other way if needed), then the backend send the actual render request to nexrender-server using the secret value.

As for backend implementation of how to store the secret value I'd recommend environment variables for the server, client, and worker via whichever way works for your setup.

If your secret value is leaked out to the public and your server is publically available then yes, it is possible for anyone with the secret value to send renders to nexrender-server without limit until the secret value is changed.

**Comment by limzykenneth** [comment]
I don't have any experience with Webflow but from what I understand Webflow is primarily frontend only and so will not be a secure place to store the secret value (anyone can see that value and make arbitrary render request to your server). So you will not be placing the `createClient` code there (it probably won't work as well since it probably needs a node.js environment to run).

In terms of environment variables it differs between unix and windows but the general idea is described in the [twelve factor app](https://12factor.net/config) design system. You can look up how to run a node.js program with environment variables value for your system.

You can of course also hard code the secret value into your server side code and that will work depending on your requirements and situation but may not be suitable in other situation, this needs to be judged on a slightly more case by case basis.
