### ISSUE TITLE
Control nexrender via API from Java Application

### ISSUE THREAD

**Issue by youzhajun** [inlife/nexrender#872]
I want to invoke the nexsender API through a Java service. I want the nexsender server to call back to the Java server to tell me that the task was successful when the task status changes, rather than periodically requesting the task status query interface

`"onChange": Function,
    "onRenderProgress": Function,
    "onRenderError": Function`

Are these configurations used? How do I initiate an http request and carry the ID and task status through this?

**Comment by inlife** [comment]
You can take a look at the HTTP API that nexrender-server offers:
https://github.com/inlife/nexrender/tree/master/packages/nexrender-server

And just in case, here is the visualization of how this network setup would look like:
![](https://user-images.githubusercontent.com/2182108/77616726-02443700-6f3b-11ea-8e27-b59656d9efe1.png)

**Comment by youzhajun** [comment]
@inlife  Yes, I have already called the server to create a task through the API. I don't think I have expressed my problem very well. I want NexSender to notify Java when the task is completed, rather than constantly requesting NexSender to inquire about the task status.

**Comment by youzhajun** [comment]
Which attribute should be used to configure and callback Java addresses and parameters?

**Comment by youzhajun** [comment]
Can you provide a simple example of letting nexsender request when the task is completed http://test.com/updateTaskStatus Interface and carry task i

**Comment by inlife** [comment]
Well, by default, the is the expected behavior, and both nexrender-worker and nexrender-api packages also work the same way, they constantly POLL the API server for any updates on a regular basis.

If you want something more advanced, you could take a look into job actions, more specifically, I belive someone developed an action with Webhook. It could be used when you are creating a job on your Java side, to provide the URL which should be triggered when render finishes.

**Comment by youzhajun** [comment]
@inlife Thank you！Do you have any relevant information on this aspect. Because I feel that it is a waste of resources for the Java server to frequently request the nexsender server to create http links
