### ISSUE TITLE
Prevent log creation

### ISSUE THREAD

**Issue by KonkenBonken** [inlife/nexrender#877]
Is there any way to prevent nexrender/aerender to create a `.log` file?
I have no need for log files filling up my rendering directory

**Comment by inlife** [comment]
Hey @KonkenBonken 

I think there is no way of doing that right now, but I'll think about adding something like this.

Ideally, the best way would be to move the log file from the root folder to the actual project folder where rendering is happening, so that it can later be picked up by the auto-cleaner.

**Comment by inlife** [comment]
Introduced a new feature with an environment flag that places the aerender log file into the project folder. To enable it, define and set NEXRENDER_ENABLE_AELOG_PROJECT_FOLDER to true in in your OS or CLI env context
