### ISSUE TITLE
how write function onRenderError in php

### ISSUE THREAD

**Issue by RezaRamezanisani** [inlife/nexrender#887]
hello i use form nexrender-server.exe and nexrender-worker.exe i request to nexrender with CURL php in laravel this is my job in controller laravel:
`[
                'template' => $template,
                'assets'   => array_values($this->assets),
                  'onRenderError' => Function
]`
i don't know how write function onRenderError in code php if i inside function in string i see a error TypeError: string "(job, value) => console.log('testing onRenderProgress:', value)" is not a function
how this is senario

**Comment by limzykenneth** [comment]
It is not possible to use `onRenderProgress` or `onRenderError` with nexrender-server/worker setup, or any other setup that uses JSON (including calling the API through PHP). That is because JSON is not able to encode functions. These callbacks are only available for programmatic use, ie. using @nexrender/core directly in Javascript.
