### ISSUE TITLE
AEP Files Parser?

### ISSUE THREAD

**Issue by morjanmihail** [inlife/nexrender#950]
I love this library and I'm using it with NodeJS. I'm wondering if there is any plan for integrating an AEP files parser, to check the layers and composition from After Effects projects?

So far, I only saw one GoLang project (boltframe/aftereffects-aep-parser) that's a bit outdated and is missing a lot of info, and one python project (python-lotthie) that I'm fighting with tons of issues.

Thank you for your hard work!

Have a good day,
Mihai

**Comment by inlife** [comment]
Hey there,

So far, I have yet to see a reliable solution on nodejs that can do that. The AEP binary file protocol is complex, with some occasional changes introduced by Adobe. And unless there is a dedicated effort behind it, it would become a very unreliable feature.

If you are aware of such solution, please let me know!

**Comment by phlexib** [comment]
Your best chance is saving aexp files. 
it’s an XML version of your project so more readable and parse able but still a real pain.

**Comment by JamesBotterill** [comment]
I've been thinking about this in the past, my conclusion was some sort of AE plugin which would export the data you need from a plugin GUI from with AE itself. 

Never went much further down that rabbit hole though.

**Comment by inlife** [comment]
That is the approach to how the bodymovin plugin works, essentially.

**Comment by tinogithub** [comment]
Because I have struggled writing a test unit for my extendscripts, I might have an idea.
The way to read some project information would be to write a little extendscript that is called via commandline:
afterfx.com -noui -r "myscript.jsx" 
This script writes all information of a loaded project in a json file which then needs to be parsed by our main script that called the afterfx.com command in the first place.
This way you can read all information from a project file, I assume.

And I think it will take as much time as reading the compositions into Adobe Premiere. Which takes some time in my experience. Maybe they use the same way :)
